- name: Get all reservations
  community.general.xml:
    path: /conf/config.xml
    xpath: "/opnsense/dhcpd/{{ item }}/staticmap/mac"
    content: text
  loop: "{{ managed_interfaces }}"
  register: reservation_hits

- name: Format reservations by interface
  ansible.builtin.set_fact:
    cacheable: true
    reservations: >-
      {{
        (reservations | default([]))
        + (item.matches | map('combine', { 'interface': item.item }))
      }}
  with_items: "{{ reservation_hits.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Format allocated reservations
  ansible.builtin.set_fact:
    cacheable: true
    formatted_resv: >-
      {{
        (formatted_resv | default([]))
        + [{ 'interface': item.interface, 'mac': item.mac }]
      }}
  with_items: "{{ dhcp_reservations }}"
  loop_control:
    label: "{{ item.mac }}"

- name: Find unmanaged reservations
  ansible.builtin.set_fact:
    cacheable: true
    unmanaged_resv: >-
      {{ ansible_facts.reservations
        | difference(ansible_facts.formatted_resv)
      }}

- name: Remove untracked reservation from config
  community.general.xml:
    path: /conf/config.xml
    xpath: "/opnsense/dhcpd/{{ item.interface }}/staticmap[mac=\"{{ item.mac }}\"]"
    pretty_print: true
    state: absent
    backup: false
  register: remove_config
  loop: "{{ ansible_facts.unmanaged_resv }}"
  loop_control:
    label: "{{ item.mac }} on {{ item.interface }}"
  notify:
    - Restart dhcpd service
